config/routes.rb
Rails.application.routes.draw do
  

  devise_for :admin, skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }
  
  devise_for :users, skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }
  
  #管理者側のルーティング設定
  namespace :admin do
    resources :fish, only: [:index, :new, :create, :show, :edit, :update, :destroy]
    resources :genres, only: [:index, :create, :edit, :update, :destroy]
    resources :users, only: [:index, :show, :edit, :update]
    resources :post_comments, only: [:destroy]
    resources :posts, only: [:index, :show] do
      resources :post_comments, only: [:destroy]
    end
  end
  
  #ユーザ側のルーティング設定
  scope module: :public do
    root to: "homes#top"
    get 'homes/about' => 'homes#about', as: 'about'
    resources :posts, only: [:new, :create, :index, :show, :edit, :update, :destroy] do
      resource :likes, only: [:create, :destroy]
      resources :post_comments, only: [:create, :destroy]
      get :search, on: :collection
    end
    resources :users, only: [:edit, :update, :index, :show] do
      get 'users/data' => 'users#data'
      get :likes, on: :collection
    end
    resources :fish, only: [:index, :show]
    get 'users/data' => 'users#data'
    get 'users/unsubscribe' => 'users#unsubscribe'
    patch 'users/withdrawal' => 'users#withdrawal'
  end
  
  #ゲストユーザ用のルーティング設定
  devise_scope :user do
    post 'public/guest_sign_in', to: 'public/sessions#guest_sign_in'
  end
end

app/models/fish.rb
class Fish < ApplicationRecord
  belongs_to :genre
  # has_many :post_tags, dependent: :destroy
  has_many :posts#, through: :post_tags
  has_one_attached :image

  def get_image(width, height)
    unless image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
      image.variant(resize_to_limit: [width, height]).processed
  end
end

app/controllers/admin/fish_controller.rb
class Admin::FishController < ApplicationController
  
  def index
    @fishes = Fish.all
  end

  def new
    @fish = Fish.new
  end

  def create
    @fish = Fish.new(fish_params)
    @fish.save
    redirect_to admin_fish_index_path
  end

  def show
    @fish = Fish.find(params[:id])
  end

  def edit
    @fish = Fish.find(params[:id])
  end
  
  def update
    @fish = Fish.find(params[:id])
    @fish.update(fish_params)
    redirect_to admin_fish_index_path
  end
  
  def destroy
    @fish = Fish.find(params[:id])
    @fish.destroy
    redirect_to admin_fish_index_path
  end
  
private
  def fish_params
    params.require(:fish).permit(:genre_id, :fish_name, :introduction, :season, :recommendation, :image)
  end
end

app/helpers/admin/fish_helper.rb
module Admin::FishHelper
end

app/views/admin/fish/edit.html.erb
<div class="container">
  <div class="row mt-3">
    <div class="col-offset-2 col-lg-8 mx-auto">
      <table class="table table-striped table-dark">
        <%= form_with model: @fish, url: admin_fish_path, method: :patch do |f| %>
          <tr><th>魚種ジャンル</th><td><%= f.collection_select :genre_id, Genre.all, :id, :name , { include_blank: '選択してください'}, {class: 'form-controll', required: true } %></td></tr>
          <tr><th>魚種名</th><td><%= f.text_field :fish_name %></td></tr>
          <tr><th>豆知識</th><td><%= f.text_area :introduction, size: '40' %></td></tr>
          <tr><th>旬</th><td><%= f.text_area :season, size: '40' %></td></tr>
          <tr><th>おすすめの食べ方</th><td><%= f.text_area :recommendation, size: '40' %></td></tr>
          <tr><th>画像</th><td><%= f.file_field :image, accept: "image/*" %></td></tr>
          <tr><th><%= f.submit "変更を保存", class: 'btn btn-md btn-success' %></th><td></td></tr>
        <% end %>
      </table>
    </div>
  </div>
</div>

app/views/admin/fish/index.html.erb
<div class="container">
  <div class="row mt-3">
    <div class="col-offset-2 col-lg-8 mx-auto">
      <%= link_to "新規作成", new_admin_fish_path, class: 'btn btn-md btn-success' %>
    </div>
  </div>
  <div class="row mt-3">
    <div class="col-offset-2 col-lg-8 mx-auto">
      <table class="table table-dark">
        <thead>
          <tr>
            <th>魚種名</th>
            <th>画像</th>
            <th></th>
            <th></th>
          </tr>
        </thead>
        <% @fishes.each do |fish| %>
        <tbody>
          <tr>
            <td><%= fish.fish_name %></td>
            <td><%= image_tag fish.get_image(100,100), class: "img-fluid" %></td>
            <td><%= link_to "編集", edit_admin_fish_path(fish.id), class: 'btn btn-md btn-info' %></td>
            <td><%= link_to "削除", admin_fish_path(fish.id), method: :delete, class: 'btn btn-md btn-danger' %></td>
          </tr>
        </tbody>
        <% end %>
      </table>
    </div>
  </div>
</div>

app/views/admin/fish/new.html.erb
<div class="container">
  <div class="row mt-3">
    <div class="col-offset-2 col-lg-8 mx-auto">
      <table class="table table-striped table-dark">
        <%= form_with model: @fish, url: admin_fish_index_path, method: :post do |f| %>
          <tr><th>魚種ジャンル</th><td><%= f.collection_select :genre_id, Genre.all, :id, :name , { include_blank: '選択してください'}, {class: 'form-controll', required: true } %></td></tr>
          <tr><th>魚種名</th><td><%= f.text_field :fish_name %></td></tr>
          <tr><th>豆知識</th><td><%= f.text_area :introduction, size: '40' %></td></tr>
          <tr><th>旬</th><td><%= f.text_area :season, size: '40' %></td></tr>
          <tr><th>おすすめの食べ方</th><td><%= f.text_area :recommendation, size: '40' %></td></tr>
          <tr><th>画像</th><td><%= f.file_field :image, accept: "image/*" %></td></tr>
          <tr><th><%= f.submit "新規登録", class: 'btn btn-md btn-success' %></th><td></td></tr>
        <% end %>
      </table>
    </div>
  </div>
</div>

app/views/admin/fish/show.html.erb
<h1>Admin::Fish#show</h1>
<p>Find me in app/views/admin/fish/show.html.erb</p>