config/routes.rb
Rails.application.routes.draw do
  

  devise_for :admin, skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }
  
  devise_for :users, skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }
  
  #管理者側のルーティング設定
  namespace :admin do
    resources :fish, only: [:index, :new, :create, :show, :edit, :update, :destroy]
    resources :genres, only: [:index, :create, :edit, :update, :destroy]
    resources :users, only: [:index, :show, :edit, :update]
    resources :post_comments, only: [:destroy]
    resources :posts, only: [:index, :show] do
      resources :post_comments, only: [:destroy]
    end
  end
  
  #ユーザ側のルーティング設定
  scope module: :public do
    root to: "homes#top"
    get 'homes/about' => 'homes#about', as: 'about'
    resources :posts, only: [:new, :create, :index, :show, :edit, :update, :destroy] do
      resource :likes, only: [:create, :destroy]
      resources :post_comments, only: [:create, :destroy]
      get :search, on: :collection
    end
    resources :users, only: [:edit, :update, :index, :show] do
      get 'users/data' => 'users#data'
      get :likes, on: :collection
    end
    resources :fish, only: [:index, :show]
    get 'users/data' => 'users#data'
    get 'users/unsubscribe' => 'users#unsubscribe'
    patch 'users/withdrawal' => 'users#withdrawal'
  end
  
  #ゲストユーザ用のルーティング設定
  devise_scope :user do
    post 'public/guest_sign_in', to: 'public/sessions#guest_sign_in'
  end
end

app/models/genre.rb
class Genre < ApplicationRecord
end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController

  def index
    @genre = Genre.new
    @genres = Genre.all
  end
  
  def create
    @genre = Genre.new(genre_params)
    @genre.save
    redirect_to admin_genres_path
  end
  
  def edit
    @genre = Genre.find(params[:id])
  end
  
  def update
    @genre = Genre.find(params[:id])
    @genre.update(genre_params)
    redirect_to admin_genres_path
  end
  
  def destroy
    @genre = Genre.find(params[:id])
    @genre.destroy
    redirect_to admin_genres_path
  end

private
  def genre_params
    params.require(:genre).permit(:name)
  end

end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/views/admin/genres/edit.html.erb
<div class="container">
  <div class="row mt-3">
    <div class="col-offset-2 col-lg-8 mx-auto">
      <%= form_with model: @genre, url: admin_genres_path, method: :post do |f| %>
        <%= f.label :name, "魚種ジャンル" %>
        <%= f.text_field :name %>
        <%= f.submit '変更を保存', class: 'btn btn-md btn-success' %>
      <% end %>
    </div>
  </div>
</div>

app/views/admin/genres/index.html.erb
<div class="container">
  <div class="row mt-3">
    <div class="col-offset-2 col-lg-8 mx-auto">
      <%= form_with model: @genre, url: admin_genres_path, method: :post do |f| %>
        <%= f.label :name, "魚種ジャンル" %>
        <%= f.text_field :name %>
        <%= f.submit '新規登録', class: 'btn btn-md btn-success' %>
      <% end %>
    </div>
  </div>
  <div class="row mt-3">
    <div class="col-offset-2 col-lg-8 mx-auto">
      <table class="table table-striped table-dark">
        <thead>
          <tr>
            <th>ジャンル名</th>
            <th></th>
            <th></th>
          </tr>
        </thead>
        <% @genres.each do |genre| %>
        <tbody>
          <tr>
            <td><%= genre.name %></td>
            <td><%= link_to "編集する", edit_admin_genre_path(genre.id), class: 'btn btn-md btn-info' %></td>
            <td><%= link_to "削除する", admin_genre_path(genre.id), method: :delete, class: 'btn btn-md btn-danger' %></td>
          </tr>
        </tbody>
        <% end %>
      </table>
    </div>
  </div>
</div>