config/routes.rb
Rails.application.routes.draw do
  

  devise_for :admin, skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }
  
  devise_for :users, skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }
  
  #管理者側のルーティング設定
  namespace :admin do
    resources :fish, only: [:index, :new, :create, :show, :edit, :update, :destroy]
    resources :genres, only: [:index, :create, :edit, :update, :destroy]
    resources :users, only: [:index, :show, :edit, :update]
    resources :post_comments, only: [:destroy]
    resources :posts, only: [:index, :show] do
      resources :post_comments, only: [:destroy]
    end
  end
  
  #ユーザ側のルーティング設定
  scope module: :public do
    root to: "homes#top"
    get 'homes/about' => 'homes#about', as: 'about'
    resources :posts, only: [:new, :create, :index, :show, :edit, :update, :destroy] do
      resource :likes, only: [:create, :destroy]
      resources :post_comments, only: [:create, :destroy]
      get :search, on: :collection
    end
    resources :users, only: [:edit, :update, :index, :show] do
      get 'users/data' => 'users#data'
      get :likes, on: :collection
    end
    resources :fish, only: [:index, :show]
    get 'users/data' => 'users#data'
    get 'users/unsubscribe' => 'users#unsubscribe'
    patch 'users/withdrawal' => 'users#withdrawal'
  end
  
  #ゲストユーザ用のルーティング設定
  devise_scope :user do
    post 'public/guest_sign_in', to: 'public/sessions#guest_sign_in'
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_one_attached :profile_image
  has_many :posts, dependent: :destroy
  has_many :post_comments, dependent: :destroy
  has_many :likes, dependent: :destroy
  
  validates :last_name, length: {minimum: 2, maximum: 20}, uniqueness: { case_sensitive: false }
  validates :first_name, length: {minimum: 2, maximum: 20}, uniqueness: { case_sensitive: false }
  validates :last_name_kana, length: {minimum: 2, maximum: 20}, uniqueness: { case_sensitive: false }
  validates :first_name_kana, length: {minimum: 2, maximum: 20}, uniqueness: { case_sensitive: false }
  validates :telephone_number, length: {maximum: 20}
  validates :email, length: {maximum: 30}
  
  def self.guest
    find_or_create_by!(email: 'guest@example.com') do |user|
      user.password = SecureRandom.urlsafe_base64
      #user.confirmed_at = Time.now  # Confirmable を使用している場合は必要
      # 例えば name を入力必須としているならば， user.name = "ゲスト" なども必要
      user.last_name = "ゲスト"
      user.first_name = "ログイン"
      user.last_name_kana = "ゲスト"
      user.first_name_kana = "ログイン"
    end
  end
  
  def get_profile_image(width, height)
    unless profile_image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
      profile_image.variant(resize_to_limit: [width, height]).processed
  end
  
  def get_image(width, height)
    unless image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
      image.variant(resize_to_limit: [width, height]).processed
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController

  def index
    @users = User.all
  end
  
  def show
    @user = User.find(params[:id])
  end
  
  def edit
    @user = User.find(params[:id])
  end
  
  def update
    @user = User.find(params[:id])
    @user.update(user_params)
    redirect_to admin_users_path
  end

private

  def user_params
    params.require(:user).permit(:email, :last_name, :first_name, :last_name_kana, :first_name_kana, :telephone_number, :is_deleted)
  end

end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/views/admin/users/edit.html.erb
<div class="container">
  <div class="row mt-3">
    <div class="col-offset-2 col-lg-8 mx-auto">
      <%= form_with model: @user, url: admin_user_path, method: :patch do |f| %>
      <table class="table table-striped table-dark">
          <tr><th>会員ID</th><td><%= @user.id %></td></tr>
          <tr><th>氏名</th><td><%= f.text_field :last_name %><%= f.text_field :first_name %></td></tr>
          <tr><th>フリガナ</th><td><%= f.text_field :last_name_kana %><%= f.text_field :first_name_kana %></td></tr>
          <tr><th>メールアドレス</th><td><%= f.email_field :email %></td></tr>
          <tr><th>電話番号</th><td><%= f.text_field :telephone_number %></td></tr>
          <tr><th>会員ステータス</th>
          <td>
            <%= f.radio_button :is_deleted, :false %>
            <%= f.label :is_delete, "有効" %>
            <%= f.radio_button :is_deleted, :true %>
            <%= f.label :is_delete, "退会" %>
          </td></tr>
          <tr><th><%= f.submit "変更を保存", class: 'btn btn-md btn-success' %></th><td></td></tr>
      </table>
      <% end %>
    </div>
  </div>
</div>

app/views/admin/users/index.html.erb
<div class="container">
  <div class="row mt-3">
    <div class="col-offset-2 col-lg-8 mx-auto">
    <table class="table table-striped table-dark">
      <thead>
        <tr>
          <th>会員ID</th>
          <th>ユーザ名</th>
          <th>ユーザ画像</th>
          <th></th>
          <th></th>
        </tr>
      </thead>
      <% @users.each do |user| %>
      <tbody>
        <tr>
          <td><%= user.id %></td>
          <td><%= link_to admin_user_path(user.id) do %><%= user.last_name %><%= user.first_name %><% end %></td>
          <td><%= image_tag user.get_profile_image(100,100), class: "img-fluid" %></td>
          <td><%= user.is_deleted ? '退会' : '有効' %></td>
          <td><%= link_to "編集する", edit_admin_user_path(user.id), class: 'btn btn-md btn-info' %></td>
        </tr>
      </tbody>
      <% end %>
    </table>
    
    
    
  </div>
</div>

app/views/admin/users/show.html.erb
<div class="container">
  <div class="row mt-3">
    <div class="col-offset-2 col-lg-8 mx-auto">
      <table class="table table-striped table-dark">
          <tr><th>会員ID</th><td><%= @user.id %></td></tr>
          <tr><th>氏名</th><td><%= @user.last_name %><%= @user.first_name %></td></tr>
          <tr><th>フリガナ</th><td><%= @user.last_name_kana %><%= @user.first_name_kana %></td></tr>
          <tr><th>メールアドレス</th><td><%= @user.email %></td></tr>
          <tr><th>電話番号</th><td><%= @user.telephone_number %></td></tr>
          <tr><th>会員ステータス</th><td><%= @user.is_deleted ? '退会' : '有効' %></td></tr>
          <tr><th></th><td><%= link_to "編集する", edit_admin_user_path(@user.id) %></td></tr>
      </table>
    </div>
  </div>
</div>