config/routes.rb
Rails.application.routes.draw do
  

  devise_for :admin, skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }
  
  devise_for :users, skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }
  
  #管理者側のルーティング設定
  namespace :admin do
    resources :fish, only: [:index, :new, :create, :show, :edit, :update, :destroy]
    resources :genres, only: [:index, :create, :edit, :update, :destroy]
    resources :users, only: [:index, :show, :edit, :update]
    resources :post_comments, only: [:destroy]
    resources :posts, only: [:index, :show] do
      resources :post_comments, only: [:destroy]
    end
  end
  
  #ユーザ側のルーティング設定
  scope module: :public do
    root to: "homes#top"
    get 'homes/about' => 'homes#about', as: 'about'
    resources :posts, only: [:new, :create, :index, :show, :edit, :update, :destroy] do
      resource :likes, only: [:create, :destroy]
      resources :post_comments, only: [:create, :destroy]
      get :search, on: :collection
    end
    resources :users, only: [:edit, :update, :index, :show] do
      get 'users/data' => 'users#data'
      get :likes, on: :collection
    end
    resources :fish, only: [:index, :show]
    get 'users/data' => 'users#data'
    get 'users/unsubscribe' => 'users#unsubscribe'
    patch 'users/withdrawal' => 'users#withdrawal'
  end
  
  #ゲストユーザ用のルーティング設定
  devise_scope :user do
    post 'public/guest_sign_in', to: 'public/sessions#guest_sign_in'
  end
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/fish.rb
class Fish < ApplicationRecord
  belongs_to :genre
  # has_many :post_tags, dependent: :destroy
  has_many :posts#, through: :post_tags
  has_one_attached :image

  def get_image(width, height)
    unless image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
      image.variant(resize_to_limit: [width, height]).processed
  end
end

app/models/genre.rb
class Genre < ApplicationRecord
end

app/models/like.rb
class Like < ApplicationRecord

  belongs_to :user
  belongs_to :post

end

app/models/post.rb
class Post < ApplicationRecord
  has_one_attached :image
  belongs_to :user
  belongs_to :fish
  # has_many :post_tags, dependent: :destroy
  # has_many :fish, through: :post_tags
  
  has_many :post_comments, dependent: :destroy
  has_many :likes, dependent: :destroy
  
  validates :title, presence: true
  validates :content, presence: true
  validates :recipe, presence: true
  validates :method, presence: true
  validates :image, presence: true

  
  def get_image(width, height)
    unless image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
      image.variant(resize_to_limit: [width, height]).processed
  end
  
  def liked_by?(user)
    likes.exists?(user_id: user.id)
  end
  
end

app/models/post_comment.rb
class PostComment < ApplicationRecord
  
  belongs_to :user
  belongs_to :post
end

app/models/post_tag.rb
class PostTag < ApplicationRecord
  belongs_to :post
  belongs_to :fish
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_one_attached :profile_image
  has_many :posts, dependent: :destroy
  has_many :post_comments, dependent: :destroy
  has_many :likes, dependent: :destroy
  
  validates :last_name, length: {minimum: 2, maximum: 20}, uniqueness: { case_sensitive: false }
  validates :first_name, length: {minimum: 2, maximum: 20}, uniqueness: { case_sensitive: false }
  validates :last_name_kana, length: {minimum: 2, maximum: 20}, uniqueness: { case_sensitive: false }
  validates :first_name_kana, length: {minimum: 2, maximum: 20}, uniqueness: { case_sensitive: false }
  validates :telephone_number, length: {maximum: 20}
  validates :email, length: {maximum: 30}
  
  def self.guest
    find_or_create_by!(email: 'guest@example.com') do |user|
      user.password = SecureRandom.urlsafe_base64
      #user.confirmed_at = Time.now  # Confirmable を使用している場合は必要
      # 例えば name を入力必須としているならば， user.name = "ゲスト" なども必要
      user.last_name = "ゲスト"
      user.first_name = "ログイン"
      user.last_name_kana = "ゲスト"
      user.first_name_kana = "ログイン"
    end
  end
  
  def get_profile_image(width, height)
    unless profile_image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
      profile_image.variant(resize_to_limit: [width, height]).processed
  end
  
  def get_image(width, height)
    unless image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
      image.variant(resize_to_limit: [width, height]).processed
  end
end

app/controllers/admin/fish_controller.rb
class Admin::FishController < ApplicationController
  
  def index
    @fishes = Fish.all
  end

  def new
    @fish = Fish.new
  end

  def create
    @fish = Fish.new(fish_params)
    @fish.save
    redirect_to admin_fish_index_path
  end

  def show
    @fish = Fish.find(params[:id])
  end

  def edit
    @fish = Fish.find(params[:id])
  end
  
  def update
    @fish = Fish.find(params[:id])
    @fish.update(fish_params)
    redirect_to admin_fish_index_path
  end
  
  def destroy
    @fish = Fish.find(params[:id])
    @fish.destroy
    redirect_to admin_fish_index_path
  end
  
private
  def fish_params
    params.require(:fish).permit(:genre_id, :fish_name, :introduction, :season, :recommendation, :image)
  end
end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController

  def index
    @genre = Genre.new
    @genres = Genre.all
  end
  
  def create
    @genre = Genre.new(genre_params)
    @genre.save
    redirect_to admin_genres_path
  end
  
  def edit
    @genre = Genre.find(params[:id])
  end
  
  def update
    @genre = Genre.find(params[:id])
    @genre.update(genre_params)
    redirect_to admin_genres_path
  end
  
  def destroy
    @genre = Genre.find(params[:id])
    @genre.destroy
    redirect_to admin_genres_path
  end

private
  def genre_params
    params.require(:genre).permit(:name)
  end

end

app/controllers/admin/posts_controller.rb
class Admin::PostsController < ApplicationController
  def index
    @posts = Post.all
  end

  def show
    @post = Post.find(params[:id])
    @user = @post.user
    @post_comment = PostComment.new
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController

  def index
    @users = User.all
  end
  
  def show
    @user = User.find(params[:id])
  end
  
  def edit
    @user = User.find(params[:id])
  end
  
  def update
    @user = User.find(params[:id])
    @user.update(user_params)
    redirect_to admin_users_path
  end

private

  def user_params
    params.require(:user).permit(:email, :last_name, :first_name, :last_name_kana, :first_name_kana, :telephone_number, :is_deleted)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/helpers/admin/fish_helper.rb
module Admin::FishHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/post_comments_helper.rb
module Admin::PostCommentsHelper
end

app/helpers/admin/posts_helper.rb
module Admin::PostsHelper
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admin/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Scale</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="background_image">
    <header class="sticky-top">
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark text-white">
        <a>
          <%= link_to root_path, data: {"turbolinks" => false} do %><%= image_tag 'logo1.png', :width => "60", class: "img-fluid" %><% end %>
        </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
          <div class="collapse navbar-collapse" id="navbarNavDropdown">
           <ul class="navbar-nav ml-auto">
            <% if admin_signed_in? %>
              <% if request.fullpath.include? "/admin" %>
              <li class="nav-item ml-3">
                <button class="btn btn-outline-secondary" type="button">
                <%= link_to "ログアウト", destroy_admin_session_path, method: :delete, class: 'text-white' %>
                </button>
              </li>
              <li class="nav-item ml-3">
                <button class="btn btn-outline-secondary" type="button">
                <%= link_to "魚種一覧", admin_fish_index_path, class: 'text-white' %>
                </button>
              </li>
              <li class="nav-item ml-3">
                <button class="btn btn-outline-secondary" type="button">
                <%= link_to "ジャンル一覧", admin_genres_path, class: 'text-white' %>
                </button>
              </li>
              <li class="nav-item ml-3">
                <button class="btn btn-outline-secondary" type="button">
                <%= link_to "ユーザ一覧", admin_users_path, class: 'text-white' %>
                </button>
              </li>
              <li class="nav-item ml-3">
                <button class="btn btn-outline-secondary" type="button">
                <%= link_to "コメント管理", admin_posts_path, class: 'text-white' %>
                </button>
              </li>
              <% else %>
              <li class="nav-item ml-3">
                <button class="btn btn-outline-secondary" type="button">
                <%= link_to "About", about_path, class: 'text-white' %>
                </button>
              </li>
              <li class="nav-item ml-3">
                <button class="btn btn-outline-secondary" type="button">
                <%= link_to "新規登録", new_user_registration_path, class: 'text-white' %>
                </button>
              </li>
              <li class="nav-item ml-3">
                <button class="btn btn-outline-secondary" type="button">
                <%= link_to "ログイン", new_user_session_path, class: 'text-white' %>
                </button>
              </li>
              <li class="nav-item ml-3">
                <button class="btn btn-outline-secondary" type="button">
                <%= link_to "ユーザ一覧", admin_users_path, class: 'text-white' %>
                </button>
              </li>
              <% end %>
            <% elsif user_signed_in? %>
            <li class="nav-item ml-3">
              <button class="btn btn-outline-secondary" type="button">
              <%= link_to "マイページ", user_path(current_user.id), class: 'text-white' %>
              </button>
            </li>
            <li class="nav-item ml-3">
              <button class="btn btn-outline-secondary" type="button">
              <%= link_to "魚種一覧", fish_index_path, class: 'text-white' %>
              </button>
            </li>
            <li class="nav-item ml-3">
              <button class="btn btn-outline-secondary" type="button">
              <%= link_to "投稿一覧", posts_path, class: 'text-white' %>
              </button>
            </li>
            <li class="nav-item ml-3">
              <button class="btn btn-outline-secondary" type="button">
              <%= link_to "新規投稿", new_post_path, class: 'text-white' %>
              </button>
            </li>
            <li class="nav-item ml-3">
              <button class="btn btn-outline-secondary" type="button">
              <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: 'text-white' %>
              </button>
            </li>
          <% else %>
            <li class="nav-item ml-3">
              <button class="btn btn-outline-secondary" type="button">
              <%= link_to "About", about_path, class: 'text-white' %>
              </button>
            </li>
            <li class="nav-item ml-3">
              <button class="btn btn-outline-secondary" type="button">
              <%= link_to "新規登録", new_user_registration_path, class: 'text-white' %>
              </button>
            </li>
            <li class="nav-item ml-3">
              <button class="btn btn-outline-secondary" type="button">
              <%= link_to "ログイン", new_user_session_path, class: 'text-white' %>
              </button>
            </li>
            <li class="nav-item ml-3">
              <button class="btn btn-outline-secondary" type="button">
              <%= link_to 'ゲストログイン（閲覧用）', public_guest_sign_in_path, method: :post, class: 'text-white' %>
              </button>
            </li>
          <% end %>
          </ul>
        </div>
      </nav>
    </header>
    <%= yield %>
  </body>
</html>